name: Continuous Integration

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    compile-and-test:
        runs-on: ubuntu-22.04

        steps:
            - name: Install System Updates
              run: sudo apt-get update

            - name: Print Dependency Versions
              run: |
                  cat /etc/os-release
                  gcc --version

            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Compile and Run Unit Tests
              run: sh ./compile-run-unit-tests.sh
